=== jeremylong/DependencyCheck/dependency-check-core/src/main/resources/schema/suppression.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="suppressions" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="https://www.owasp.org/index.php/OWASP_Dependency_Check_Suppression">
    <xs:element name="suppressions">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="suppress">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="1">
                            <xs:sequence minOccurs="0" maxOccurs="1">
                                <xs:element name="notes" type="xs:string"/>
                            </xs:sequence>
                            <xs:choice minOccurs="0" maxOccurs="1">
                                <xs:element name="filePath">
                                    <xs:complexType>
                                        <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                                <xs:attribute name="regex" use="optional" type="xs:boolean" default="false"/>
                                                <xs:attribute name="caseSensitive" use="optional" type="xs:boolean" default="false"/>
                                            </xs:extension>
                                        </xs:simpleContent>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="sha1" type="xs:string"/>
                            </xs:choice>
                            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                                <xs:choice>
                                    <xs:element name="cpe">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:attribute name="regex" use="optional" type="xs:boolean" default="false"/>
                                                    <xs:attribute name="caseSensitive" use="optional" type="xs:boolean" default="false"/>
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="cve" type="xs:string"/>
                                    <xs:element name="cwe" type="xs:string"/>
                                    <xs:element name="cvssBelow" type="xs:decimal"/>
                                </xs:choice>
                            </xs:sequence>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jeremylong/DependencyCheck/dependency-check-core/src/test/resources/suppressions.xml
<?xml version="1.0" encoding="UTF-8"?>
<suppressions
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='https://www.owasp.org/index.php/OWASP_Dependency_Check_Suppression'
    xsi:schemaLocation='https://www.owasp.org/index.php/OWASP_Dependency_Check_Suppression suppression.xsd'>
    <suppress>
        <notes><![CDATA[
        This suppresses cpe:/a:csv:csv:1.0 for some.jar in the "c:\path\to" directory.
        ]]></notes>
        <filePath>c:\path\to\some.jar</filePath>
        <cpe>cpe:/a:csv:csv:1.0</cpe>
    </suppress>
    <suppress base="true">
        <notes><![CDATA[
        This suppresses any jboss:jboss cpe for any test.jar in any directory.
        ]]></notes>
        <filePath regex="true">.*\btest\.jar</filePath>
        <cpe>cpe:/a:jboss:jboss</cpe>
    </suppress>
    <suppress>
        <notes><![CDATA[
        This suppresses a specific cve for any test.jar in any directory.
        ]]></notes>
        <filePath regex="true">.*\btest\.jar</filePath>
        <cve>CVE-2013-1337</cve>
    </suppress>
    <suppress>
        <notes><![CDATA[
        This suppresses a specific cve for any dependency in any directory that has the specified sha1 checksum.
        ]]></notes>
        <sha1>384FAA82E193D4E4B0546059CA09572654BC3970</sha1>
        <cve>CVE-2013-1337</cve>
    </suppress>
    <suppress>
        <notes><![CDATA[
        This suppresses all CVE entries that have a score below CVSS 7.
        ]]></notes>
        <cvssBelow>7</cvssBelow>
    </suppress>
</suppressions>
